name: Test PHP 8.x

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  release:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: ['13.*']
        php: ['8.3', '8.4']

    name: Laravel ${{ matrix.laravel }} | PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-

      - name: Install dependencies
        run: |
          composer require \
            "illuminate/support:${{ matrix.laravel }}" \
            "illuminate/contracts:${{ matrix.laravel }}" \
            --no-interaction --no-update

          composer update \
            --prefer-dist \
            --no-interaction \
            --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --testdox
